### ISSUE TITLE
GarminxHD : Missing menu for setting radar misalignment correction. 

### ISSUE THREAD

**Issue by trudK45** [opencpn-radar-pi/radar_pi#10]
You must be able to correct the angle of the radar if it is not set perfectly to the boats centerline.

**Comment by canboat** [comment]
See Advanced > Installation > Bearing alignment, now that it is enabled.

**Comment by trudK45** [comment]
The menu is present and it changes the values om the plotter but I have trouble testing it since radar overlay now seems to be not working.
