### ISSUE TITLE
MARPA

### ISSUE THREAD

**Issue by valschmidt** [opencpn-radar-pi/radar_pi#111]
This is not so much an issue but a question, and maybe a feature request.

I looked through the code and I couldn't see that you are doing anything with MARPA data (target tracking). This should be available in at least the HALO24 series. Did I miss it, and if not, any plans there? 

Thanks.

**Comment by douwefokkema** [comment]
It seems that the scanner software is doing MARPA. We do ARPA and MARPA inside the radar_pi software and don't use the target MARPA data from the scanner. When we made this the HALO24 was still unknown. We do not have specifications of the target info that the HALO scanner might transmit. I think the best we could do on short term is to use the Doppler speed info for improving our target detection and tracking. However we still lack the information of how the measured blob Doppler data is transmitted, if it is transmitted quantitatively by the scanner. We would need the relative speed for every pixel received.
