### ISSUE TITLE
PPI windows not refreshed on Mac

### ISSUE THREAD

**Issue by douwefokkema** [opencpn-radar-pi/radar_pi#112]
HugoGr reported on the forum that the radar PPI windows are frozen on Mac with Mojave. I just verified this, is fully reproducible. It seems that the Render() is not called on Mac.
I checked older commits of radar_pi, problem remains, though these versions have been tested on Mac. I assume that recent changes in O5.0 are causing this issue. I am using the released and distributed O version 5.0.0 + 9065270.

**Comment by douwefokkema** [comment]
There are 2 problems.
First is in radar_pi, beta2, not in released version. Solution has been pushed to master.
Second problem is in OpenCPN. The released version differs from the ones I compile myself. Released version does not function, my compiled versions are fine. Does Travis use different components than I use?

**Comment by keesverruijt** [comment]
Sorry closed the wrong issue

**Comment by keesverruijt** [comment]
This is fixed with plugin 5.0.1 or 5.0.3-beta2 and OpenCPN 5.0.1, see http://www.cruisersforum.com/forums/f134/opencpn-5-0-1-for-macos-mojave-10-14-5-a-220988.html
