### ISSUE TITLE
GarminxHD : Does ARPA really work?

### ISSUE THREAD

**Issue by trudK45** [opencpn-radar-pi/radar_pi#12]
I have no experience with ARPA but I am a bit confused when I look at the display.
The ship I put the cursor on is said to do 9.44 knots. I know that ship is at anchor.
There are other ARPA targets where there are no echoes.

![arpa](https://user-images.githubusercontent.com/10415016/32583501-c0791e4a-c4eb-11e7-9368-0a24cf37a203.jpg)

**Comment by canboat** [comment]
I rewrote large parts for this new versions, I wouldn't be surprised it's broken right now. ARPA is Douwe's speciality, I hope he has time to look into this.

**Comment by douwefokkema** [comment]
I tried the ARPA on the Scan_1.pcap file. Replayed with fixed position and heading. I noticed speeds in a (seemingly) anchored target. But that target moved up and down over 120 meters on my overlay. This causes the target to pick up some speed in various directions. There are also some targets that show and hide all the time. This may cause an ARPA target not to correspond to a radar blob. However, when a target is not seen in the last sweep of the radar, the ARPA target should turn yellow.
I will look into this further. A handicap in checking this is that I don't have heading info that runs simultaneous with the recording (with the Navico radar I use the heading on radar).
Hans, which recorded file is best to check ARPA?

**Comment by canboat** [comment]
Douwe,

I was wondering that maybe the different # of spokes is not accounted for correctly in the ARPA code. But let’s start with checking that ARPA still works with Navico after my rewrite for the variable radar # and spoke #.

**Comment by trudK45** [comment]
I can prepare a new .pcap and NEMA data to along with it where we do have targets.
Would this help ?
I will be out during the day but can have this ready in the evening.

**Comment by douwefokkema** [comment]
Yes, certainly worth a trial. When you output the NMEA data as UDP on the net it should be logged synchronously in the pcap file. Just take a port number (eg 5555)

**Comment by canboat** [comment]
Would you please record the NMEA (NEMA is something else) data as an UDP stream in the pcap file? That way they are synchronised in time.

You can use OpenCPN for this. Add an output UDP port 5001, IP address your broadcast IP address. for instance if your radar ethernet card has IP address 172.16.2.40 set the IP address to 172.16.2.255.

Then make sure you send all NMEA sentences (Output filtering -> click “drop sentences” and add no sentences.)

**Comment by trudK45** [comment]
I have uploaded a zipped .pcap file (ARPA_alarm.zip) with ARPA on, Alarm on. 30 sec long.
Broadcast address for NMEA data=176.16.15.255
NMEA includes : GPRMC, GPGBS, HCHDG (10 Hz) and AIS-data.

**Comment by canboat** [comment]
Oops, reopening as I used the wrong #12 instead of #26 in commit a59115e.

**Comment by douwefokkema** [comment]
Yes, ARPA is functioning as it should, at least in 58a58c12
