### ISSUE TITLE
Halo3 Doppler Encoding Question

### ISSUE THREAD

**Issue by jml1795** [opencpn-radar-pi/radar_pi#133]
Hello,

Thanks for all the hard work on putting together the radar plugin. I am working on interfacing with a Simrad Halo3 and had a few questions regarding the raw doppler encoding I was hoping somebody could provide a bit more information on. The radar plugin appears to be working well and this isn't a bug, just a question to clarify my interpretation of the code. @keesverruijt appears to be the developer of the doppler processing for the navico radars.

In NavicoReceive.cpp the raw returns are packed into a 512 element `radar_line` and it appears each byte in the array is the return for two adjacent range bins (the low and high 4 bits from each byte defining the two bins). There is some logic to determine whether those 4 bits represent a doppler value or return intensity value, and if doppler, whether the contact is approaching or receding.

What is the correct interpretation of those 4 bits? It appears a value of `0xF` is approaching, and `0xE` is receding (if `doppler_state` is non-zero), but what is the interpretation of the other values? Do they still represent a doppler field and this is a thresholding that is being applied in the radar pi? If so, is this what the `doppler_speed` field was to be used for (user-specified threshold)? Or is it that the radar only provides an indication of inbound or outbound contacts and does not expose the actual doppler measurement? In this case, are the other values set to the return intensity? In the event doppler is turned off, do they always represent return intensity? Any additional information on the correct interpretation of the return would be greatly appreciated.

Thanks again for putting the radar pi together!
John

**Comment by keesverruijt** [comment]
Hi John, 

The other values are intensity of the radar return. 
The radar does not provide the actual doppler measurement.

Remember, per "pixel" the radar can only send one data point, and they use all four bits to encode `0xF` (approaching) or `0xE` (receding). So there is no space to send the doppler speed. The doppler speed threshold is sent to the radar, and that makes the calculation internally.
