### ISSUE TITLE
FeatureRequest: two radars, different ranges overlay on one canvas

### ISSUE THREAD

**Issue by LeaseOnLife** [opencpn-radar-pi/radar_pi#134]
Use case: 
My monitor in the cockpit has limited size and resolution (1024x768) and I tend to stay away from putting O in split screen mode. My 4G radar can do A and B radar at different ranges, but I can only activate chart-overly with one. I can activate a PPI window for the second radar, but that covers part of my limited screen.

I would like to have a short range radar A with Guardzones/ARPA=ON and radar B on long range to detect squalls/bad weather, both on one canvas/chart. 
Drawing the longer range radar would require to leave the range for the shorter range transparent. Or worded differently: anything outside of the shorter range radar should then be drawn from the longer range radar.
Does above make sense?
Dirk

**Comment by keesverruijt** [comment]
I'm not sure this helps. You want to have your cake and eat it. I think you need a bigger screen.
At sea I am more and more disregarding the chart display -- it is only useful near land. At sea all I care about is AIS and radar. 
Try running with the 2 PPI windows next to each other and no chart visible at all.

An alternate which I think would make more sense is that we un-hide the PPI window when a Guard Target is detected, so besides my daughter telling you that a target is detected it would also show the PPI window. This would allow you to run with just the chart on screen (maybe even without overlay!) and pop up radar displays automatically when they get interesting?
