### ISSUE TITLE
OpenCPN 5.1.511 crashes on exit if radar_pi activated.

### ISSUE THREAD

**Issue by douwefokkema** [opencpn-radar-pi/radar_pi#136]
last log line: 18:43:15.767 MESSAGE NavicoReceive.cpp:639 radar_pi: Navico 4G B receive thread stopping. Radar_pi is 5.1.3. This is on Windows.

I reverted to O 5.1.428, no difference.

**Comment by Hakansv** [comment]
On O 5.1.511
I've tried to end O while transmitting.
I could repeat something similar only once with the Emulator. Last log entry: "Deactivating PlugIn: C:\Users\admin\AppData\Local\opencpn\plugins\radar_pi.dll"
The next five time O ended normally.
I've also tried the BR24 single and together with Emulator a couple of times. Couldn't reproduce. All times O ended normally.
Håkan

**Comment by douwefokkema** [comment]
Håkan,
You are right and so am I. Crash only occurs with oeSENC plugin enabled.
Douwe

**Comment by douwefokkema** [comment]
Earlier this crash was fully reproducible, today only on one machine in 50% of the cases. Strange. I attached Visual Studio debugger. Crash in iosfwd, see screenshot.
![ocpn_exception_after_crash](https://user-images.githubusercontent.com/7831072/81916253-e15fa000-95d3-11ea-9454-0bd93270db86.jpg)

**Comment by keesverruijt** [comment]
Sorry guys, I can't debug OpenCPN on Windows until I get home. Next time can you show the Call Stack?

**Comment by Hakansv** [comment]
Win10
Using present O beta, oeSENC and radar_pi I can't reproduce this issue.  
I'm using 3G. Is it a difference for 4G A/B?
Håkan

**Comment by douwefokkema** [comment]
Solved in f2c660. Problem was in NavicoLocate, I added a Wait() after m_locator->Shutdown.
