### ISSUE TITLE
flatpak metadata: wrong <target>

### ISSUE THREAD

**Issue by leamas** [opencpn-radar-pi/radar_pi#153]
The flatpak metadata contains `<target>flatpak</flatpak>`, should be `<target>flatpak-x86_64</flatpak>`. Effectively, this makes the plugin hidden and un-installable. See https://github.com/OpenCPN/OpenCPN/issues/2095

**Comment by Hakansv** [comment]
@leamas 
As you may have seen in radar_pi that flag is present here:
elseif (OCPN_FLATPAK)
    set(PKG_TARGET "flatpak")
    set(PKG_TARGET_ARCH "x86_64")

But PKG_TARGET_ARCH may not be useful? I'm neither aware nor the originator of this so from my side it's just a curious question.

**Comment by rgleason** [comment]
Hakan, it's confusing, but origin decisions have affected this. I think you need "flatpak-x86_64" in PKG_TARGET.

**Comment by leamas** [comment]
The problem is that when you look into the metadata template here is

    <target>${PKG_TARGET}</target>

PKG_TARGET  expands to just flatpak, so it doesn't work.  Problem is that these variables are used in multiple places, not just in the metadata. So  a safe, proper fix might involve a new variablelilke PKG_TARGET_FULL which is set up properly in PluginSetup.cmake and only used in the metadata. But I havn't looked into the details.

**Comment by leamas** [comment]
Closed (why not automatically?) by #154
