### ISSUE TITLE
on linux: winsock2.h not found

### ISSUE THREAD

**Issue by LeaseOnLife** [opencpn-radar-pi/radar_pi#161]
latest master, fresh clone, after cmake ../  then make: 

`pi_common.h:54:10: fatal error: winsock2.h: No such file or directory
   54 | #include <winsock2.h>
      |          ^~~~~~~~~~~~
compilation terminated.
`

**Comment by keesverruijt** [comment]
The plugin is using new build mechanisms where the continuous integration code is shared with all other plugins.
Unfortunately that means the build preparation has changed.

See `build.sh` in the top directory on how to build standalone.
