### ISSUE TITLE
Question: Halo3 doppler speed and velocity track

### ISSUE THREAD

**Issue by kizilkayabayram** [opencpn-radar-pi/radar_pi#172]
According to issue #133, As far I as understood halo 3 radar does not transmit any doppler measurements. Instead it returns only approaching/receding data. How this relates the velocitytrack feature? Does velocitytrack provides separate doppler speed for each point or only returns approaching/receding info? 

I'm actually looking for a way to get velocity values for each measurement from radar data and saw velcoitytrack on/of pcap file in examples folder. 

Thanks in advance.

**Comment by Hakansv** [comment]
@kizilkayabayram 
You can use the (M)ARPA function in radar_pi. 
Either set up an guard zone from the area you want to collect ARPA targets and select "ARPA On" for that zone.
Or right click near desired target and select "Acquire radar target" to start the MARPA function for the nearest target.

A (M)ARPA target acts like any other AIS target but with a round symbol. See picture
![bild](https://user-images.githubusercontent.com/7202854/123430258-443dac00-d5c8-11eb-87bc-859cc9dde5be.png)

**Comment by kizilkayabayram** [comment]
Are those measurements are based on doppler measurmenets?

**Comment by Hakansv** [comment]
All is calculated by radar_pi and has nothing to do with the Doppler function. So the ARPA function can be used with any radar scanner supported by radar_pi.

**Comment by keesverruijt** [comment]
> According to issue #133, As far I as understood halo 3 radar does not transmit any doppler measurements. 
> Instead it returns only approaching/receding data. 
> How this relates the velocitytrack feature?
This _is_ the VelocityTrack feature. 
> Does velocitytrack provides separate doppler speed for each point or only returns approaching/receding info?
Only approaching/receding info, which is a single value for every 'radar pixel'. 

> I'm actually looking for a way to get velocity values for each measurement from radar data...
This is not possible.

**Comment by kizilkayabayram** [comment]
Thanks a lot for quick and informative responses.
