### ISSUE TITLE
What support is there for saving radar data for post-processing, replay?

### ISSUE THREAD

**Issue by ForceConstant** [opencpn-radar-pi/radar_pi#178]
I was wondering if with using this plugin, can you save the radar data to look at it again? Either in or out of opencpn? 

Thanks.

**Comment by Hakansv** [comment]
@ForceConstant 
No, there's no such plugin function. 
For occasional use the Wireshark program to record and on Linux, (Mac?) Tcpreply to replay the saved file is what's used for development here.

**Comment by douwefokkema** [comment]
And if you also output your position and heading info (while sailing) to UDP / Ethernet, you will record (with Wireshark) all information about your trip combined with the radar data. You can replay your voyage completely by replaying the .pcapng file from Wireshark with TCPreplay. But be prepared for many gigabytes of data.

**Comment by ForceConstant** [comment]
ok thanks.
