### ISSUE TITLE
HALO accent light control

### ISSUE THREAD

**Issue by Hakansv** [opencpn-radar-pi/radar_pi#179]
See: https://www.cruisersforum.com/forums/f134/halo-24-accent-light-256321.html
From a manual:
> Control pedestal accent lighting
> The Halo™ Pulse Compression Radar pedestal has a blue accent light. The LED accent light has
> four light levels controlled from the radar menu.
> Note: The accent light can only be adjusted when the radar is in standby
Is this anything that can verified and traced by a Halo user?

**Comment by keesverruijt** [comment]
I tried it using my MFD but it is so garish I don't fancy it at all. I guess if you like bling you will have a 16" MFD to control it :-)

Is there anyone interested in this feature?
