### ISSUE TITLE
Import plugin on Mac

### ISSUE THREAD

**Issue by mouritzen** [opencpn-radar-pi/radar_pi#184]
Hi! 

I have made a fork of this repo and will attempt to extend the library to include both a Raymarine Quantum Q24C and a Furuno  DRS4D-NXT. I have downloaded and installed the latest release (5.2.4) of OpenCPN. 

However, i cannot figure out how to import the built plugin into OpenCPN. I have done the following:
- Install dependencies using the `ci/circleci-build-macos.sh`script
- Navigate to radar_pi/build
- Run `make tarball`

I then navigate to OpenCPN>Preferences>Plugins and select `Import plugin...`, but i am unable to select the .tar.gz file in finder. All files are just grayed out (see image).

<img width="875" alt="Screenshot 2021-10-19 at 15 04 31" src="https://user-images.githubusercontent.com/78348919/137915215-5b772f15-ec55-4137-bd4c-5561fbccaf6e.png">

Clearly i am doing something wrong, but i cannot figure out what, so i was hoping you guys might be able to help 😄 

I am running MacOS Big Sur 11.6.

**Comment by keesverruijt** [comment]
Hmm. I'm the only dev here running macOS now and then and I don't generally develop for macOS this way. But this seems to be a generic OpenCPN on macOS problem as it doesn't have anything to do with the plugin itself?

Anyway a workaround might be to run `make package`; once you have the plugin installed and it works you can remove the link deep in the OpenCPN package tree and make that a symlink to where-ever I build the plugin. This makes a new run just a restart not a re-install.

Also if you run the latest beta of OpenCPN then this was built with wxWidgets 3.1.5 not 3.1.2 so make sure you installed compatible development libraries of wxWidgets.

**Comment by mouritzen** [comment]
FIrst of all thank you both for the suggestions! I figured this might be an OpenCPN issue, but i was not sure.

I tried the beta version suggested by @bdbcat and i am now able to import the plugin, once i have selected the `darwin:10.13.6`flavor in OpenCPN. However, after enabling the plugin i am not able to start it, and the button does not appear in the drop down menu at the side. After restarting OpenCPN the plugin again appears to be uninstalled. 

When selecting default setting in the flavour selection in OpenCPN, it chooses `darwin-wx315:10.15.1`. Which setting would be correct for MacOS Big Sur 11.6? 

How can i choose which flavour the plugin is built for? 

Next i will try @keesverruijt suggestion using `make package` instead. Do you know where OpenCPN installs plugins to on Mac? 

As for the Raymarine radar, i think it's a Quantum 1? It just says Quantum on the housing, so i'm not sure. I will, however, start with the Furuno radar, as i have the complete setup available on land.

**Comment by keesverruijt** [comment]
I think the original question has been answered, so closing this issue.

**Comment by mouritzen** [comment]
@keesverruijt Yes, thank you! 

Unfortunately i have not yet finished the implementation for the Furuno radar. I have not been able to decipher the data on UDP multicast, since the packets are not always the same length, however i have managed to make some sense of the indexing and the overall structure of the packets. The control is purely TCP, so turning on/off the radar and configuring it is easy.

The boat will be stored for the winter this week, so unfortunately i will most likely not be able to work on it any more until next spring.
