### ISSUE TITLE
No Radar Pi plugin visible after successful installation on Mac

### ISSUE THREAD

**Issue by smartsourcedit** [opencpn-radar-pi/radar_pi#198]
macOS 12.3.1 with Open CPN 5.6.2 on Intel i7 Macbook Pro 13".

Radar Pi 5.0.4 downloaded from OpenCPN.org and installed (after accepting security and privacy alerts).

In /Library/Preferences/opencpn/ocpn-plugins.xml Radar Pi 5.0.4 entries are visible...

When I launch OpenCPN and go to Preferences -> Plugins, there is no RadarPI option visible (on my Mac).  They are not available for me to enable, even when I update the plugin master catalog.

**Comment by keesverruijt** [comment]
Correct. OpenCPN moved to a newer wx widgets version and the master build of the plug-in was not updated so there is no current plugin for 5.6.0 or later on macOS only. 

We are in the process of releasing a new production release. 

In the mean time, either download the plugin manually from cloudsmith or switch to the beta channel. 

https://cloudsmith.io/~opencpn-radar-pi/repos/opencpn-radar-pi-prod/packages/detail/raw/Radar-5.3.3-darwin-wx315-10.13.6-tarball/5.3.3/

**Comment by Hakansv** [comment]
@smartsourcedit 
You may try the newly released radar 5.3.3 from the OCPN plugin manager catalog master.
Please report your experiences.
Thanks

**Comment by keesverruijt** [comment]
This was fixed in 5.3.3.
