### ISSUE TITLE
GarminxHD : Circle at outer boarder on certain ranges. 

### ISSUE THREAD

**Issue by trudK45** [opencpn-radar-pi/radar_pi#20]
After the change "Refactor variable spoke length" we now get rings at the outermost limit of the range.
Probably due to presenting data to far out which then is static and not updated with radar data.

![image](https://user-images.githubusercontent.com/10415016/32701505-2ca46792-c7cf-11e7-9b0d-3454d6b49910.png)

**Comment by canboat** [comment]
Reproduced with Sea_Clutter_0.pcap, both Vertex and Shader, even with extreme range ring off.

**Comment by canboat** [comment]
interestingly, that is from a range with spoke_len = 733 == spoke_len_max...

**Comment by trudK45** [comment]
Yes but the 733 includes the header with data describing the radar data. The spoke is only 705 long i.e 28 bytes less. These 28 bytes are the "header". The length of the spoke s specified in scan_lenght_bytes_s as it is called in my document.
