### ISSUE TITLE
HALO 24 sea clutter setting resets to Harbour after a few seconds

### ISSUE THREAD

**Issue by svScoots** [opencpn-radar-pi/radar_pi#206]
The mode settings work well , thanks.  I'm not sure they are setting the sea clutter setting correctly, however.  I can set "offshore" mode and "sea clutter" stays at "harbour".  The "sea clutter" setting can be set by hitting auto and cycling through the settings but when I do that it resets to "harbour" after a few seconds" this is independent of what mode I am in, even  custom.  I'm fairly sure that the overall mode should also set "sea clutter"  on the HALO series. 
windows 10, O version 5.6.2,  radar version 5.4.1-alpha+507.98803b4

![offshore_harbour](https://user-images.githubusercontent.com/108607829/177030989-441aa0e6-0133-4b87-a92c-b16283f28ec5.jpg)

**Comment by keesverruijt** [comment]
Thanks, you are fully right. We haven't looked closely at sea clutter for Halo enough, it turns out is done very differently compared to 4G and before.
