### ISSUE TITLE
Trails Off is not saved correctly. 

### ISSUE THREAD

**Issue by douwefokkema** [opencpn-radar-pi/radar_pi#209]
After start up trails is always at 15 seconds. Trails can be set off, until shutdown and start up, then On again. 
Recorded with 4G radar on Windows 11. Can be reproduced without radar connected.

**Comment by Hakansv** [comment]
The same is also valid for Radar Overlay Canvas
If e.g. Config file "Radar0OverlayCanvas1"=1  the resulting status after a restart is Off (-1).
If I change the settings to "On" the write to config method write the correct value in the file.
So, read and write from and to the config file is probably correct but update settings goes wrong somewhere.

**Comment by keesverruijt** [comment]
Probably a side effect of the change I made to have the 'real' radar controls work on the first click.

**Comment by keesverruijt** [comment]
That is issue #195.

**Comment by douwefokkema** [comment]
The following update in ControlsDialog.h seems to solve this issue:
@@ -610,9 +610,7 @@ public:
 
         this->SetFont(m_parent->m_pi->m_font);
         m_item = item;
-        if (m_ci.names) {
-            SetState(RCS_MANUAL);
-        }
+        
         UpdateLabel(true);
     }

I have not pushed the update as these statements may have an other purpose.

**Comment by douwefokkema** [comment]
The problem is that the m_control_dialog->Create( is done after the reading of the ini file, these statements override the values in the ini file.

**Comment by keesverruijt** [comment]
Ah, I was confused by "solve the issue", but those are changes I made that _cause_ the issue. 

It should work again now.

**Comment by Hakansv** [comment]
When building on Windows using cmake --build . --target tarball I get the below message after install. There's normally no file permissions involved on Windows. Strange!
I'm in the boat on my way home so no further details for the moment.

![bild](https://user-images.githubusercontent.com/7202854/180210887-1f03a96e-8e85-4135-a426-ff4604279200.png)

**Comment by Hakansv** [comment]
One thought:
I'm using Windows and OCPN code from recent GitHUb master.
@leamas Could anything in Pluginmanager be the cause?
I'll try to debug when home.

**Comment by keesverruijt** [comment]
I don’t know about windows but on Mac and Linux the build step creates two libraries, one in the build directory that you cannot use, and one deep down in the hierarchy under the build directory. That is the one to use. 

Met vriendelijke groeten, kind regards,

Kees Verruijt

**Comment by Hakansv** [comment]
I created the tarball as usual. Then imported that to OCPN using the Pluginmanager. For radar_pi the above message appeared.
To double check I did the same for o-charts plugin and the same method yielded the same error. Obviously some bug in the latest code to OCPN. I'll try to bisect.

**Comment by Hakansv** [comment]
Sorry my bad..
I forgot the default build is Debug. When build using also "--config RelWithDebInfo" importing the tarball works as expected.

And the corrections for this issue seems to work fine. The trails settings in the config file are now reflected after a O restart.
I've to check the rest when back in the boat.
Thanks
Håkan

**Comment by Hakansv** [comment]
Now tested on the 3G. Trail settings and sea clutter preferences are now loaded from config file at start up as well as reflected in the menu after a run time change. Very good!

Another issue maybe connected to this:
Trail color changes are not reflected at run time. 
If I change start or end colors nothing happens. If I stop and restart O the changed colors are then used, so it's read from config but not changed "on the fly".
Håkan

**Comment by Hakansv** [comment]
Correction about trail color changes.
If I change color and then switch trails off and then on again the color is changed.
So maybe understandable and not much to spend efforts on?
