### ISSUE TITLE
GarminxHD : Gray areas when increasing range.

### ISSUE THREAD

**Issue by trudK45** [opencpn-radar-pi/radar_pi#21]
This refers to the PPI only. It looks like the plot memory is reset when you go to a lower range but not when you go to a higher. I have uploaded a recording, ice_video_20171112-174324.webm  to my dropbox.

**Comment by canboat** [comment]
The intended behaviour is that the target trails are zoomed in and out when you change range, e.g. in both directions.

**Comment by canboat** [comment]
Hans, can you share your dropbox with Douwe so he can take a look?

**Comment by trudK45** [comment]
I  think I already have done that. Did you try Douwe ?

**Comment by canboat** [comment]
I get weird results with trails as well, on Windows they seem to appear at strange times and on macOS they don't disappear if I set them to a low # of seconds.

**Comment by douwefokkema** [comment]
I have access to your dropbox, using Scan1 most of the time. Is there a pcap where I can see this issue (pcap with zooming on it) so I can replay this issue. I do not need a video.

**Comment by trudK45** [comment]
Jobs done.
I have uploaded a .pcap to my dropbox., Gray_areas.zip

**Comment by douwefokkema** [comment]
Thanks, I will work with it right now.

**Comment by douwefokkema** [comment]
This issue is identical to #18. See there for further reactions.

**Comment by douwefokkema** [comment]
Hans reports that grey areas are no longer there. Close this issue. Further remarks on trails under #18
