### ISSUE TITLE
Fix spin loop when GuardZone detection covers 360 degrees

### ISSUE THREAD

**Issue by keesverruijt** [opencpn-radar-pi/radar_pi#211]
When adding a circular guard zone that starts at 0.0 distance from the boat, it is possible that the guard zone detection loop finds the "main blob" which is 360 degrees around the boat. This causes a spin loop (causing the entire OpenCPN app to block.)

**Comment by douwefokkema** [comment]
In what version was this issue found? I can not reproduce on master. Commit 4bc17373 (13/01/2023) was meant to prevent this issue. If the issue is still there other corrections will be needed.

**Comment by keesverruijt** [comment]
This is an old bug from Aug 17, 2022, if you cannot reproduce great it is already fixed.
