### ISSUE TITLE
No longer in the plugin catalog for RPI?

### ISSUE THREAD

**Issue by andyrbarrow** [opencpn-radar-pi/radar_pi#219]
I just did a new install of OpenCPN on a RPI4. Using Buster 64 bit. 

When I went to re-install the Radar plugin, it wasn't there, in spite of refresh of the master catalog.

Is it no longer available for RPI?

**Comment by leamas** [comment]
we don't build for 64-bit buster, never had. You need to either use bullseye or 32-bit buster

**Comment by keesverruijt** [comment]
Your best bet is using Flatpak, this is the future for 64 bit on Linux.

**Comment by andyrbarrow** [comment]
Thanks. That worked.
