### ISSUE TITLE
AIS targets to PPI window is broken to OCPN 5.7.x

### ISSUE THREAD

**Issue by Hakansv** [opencpn-radar-pi/radar_pi#224]
Seems there may be some changed API for AIS targets to PPI in 5.7.x beta?
The Json transfer still works though.

**Comment by Hakansv** [comment]
Running on Win10 Debug in VS.
O 5.7.1 present master. Radar_pi present master.
I can brake on "PlugInAISDrawGL()" in RadarCanvas.cpp but don't understand where to look for possible cached AIS targets.


![bild](https://user-images.githubusercontent.com/7202854/229353344-9386a57e-106c-43e1-b15e-f25c3aae5f66.png)

**Comment by douwefokkema** [comment]
I also tested, first I had a crash in PlugInAISDraw(), I pulled the latest version of O, no crash anymore. It seems problem is in PlugInAISDraw(). O itself is showing AIS fine. But radar_pi is using TTM with a different symbol.

**Comment by douwefokkema** [comment]
The TTM symbol is showing fine on the overlay.

**Comment by Hakansv** [comment]
"TTM symbol on overlay.."
Is it the ARPA on chart overlay you mean?. Yes that's fine.

![bild](https://user-images.githubusercontent.com/7202854/229354485-f1b62fa5-fceb-4e58-b39a-a6391e47b1e3.png)

**Comment by Hakansv** [comment]
Douwe..
> "But radar_pi is using TTM with a different symbol."

 Where, except sending ARPA info to "PushNMEABuffer", is TTM used in radar_pi?

**Comment by douwefokkema** [comment]
Only for ARPA.
Other thing: is the chart_scale = 0 OK in yr debug output? looks strange. I will check tomorrow.

**Comment by Hakansv** [comment]
If I understand this correct PlugInAISDrawGL in RadarCanvas.cpp will send data to Pluginmanager.cpp that will use the data and 
call AISDraw() to find the PPI window and draw AIS targets on that screen position?
So far I can follow it. But I'm not sure what content would be there and what's missed since no of the AIS targets found are drawn on the PPI window. I may need help to exterminate.
![bild](https://user-images.githubusercontent.com/7202854/229373501-d79a4f0b-81f7-440e-b5b8-f774f7cc3711.png)

**Comment by keesverruijt** [comment]
Funny, I just started on this this weekend as well. I haven't gotten a full O dev env where I can trace into O yet, working on that. I've looked at O `viewport.cpp` and I don't think `chart_scale` matters, but setting it to a non-zero value will not hurt. But maybe some other viewport variable is now needed.

**Comment by keesverruijt** [comment]
Possibly lat_min/lat_max/lon_min/lon_max or bValid. Setting them certainly wouldn't be bad.

**Comment by bdbcat** [comment]
Hakan...
Not sure I am following this.  
Can you re-state the problem, functionally?

**Comment by LeaseOnLife** [comment]
Not Hakan here, but the original issue was about the AIS targets not showing on the PPI window, they did in the past and there is an option to toggle them on/off on that PPI window

![Screenshot_20230402_161146](https://user-images.githubusercontent.com/919044/229396301-01a31058-32a9-4e97-9610-fbe32974d4b2.png)

**Comment by bdbcat** [comment]
I have reproduced the error, working on a fix now.  Not a flaw in radar_pi.  It is regressive change in OCPN core involving OpenGL upgrades recently implemented.
More as I proceed.

**Comment by Hakansv** [comment]
Works fine, very good!
Thanks

**Comment by keesverruijt** [comment]
Confirmed fixed with https://github.com/OpenCPN/OpenCPN/commit/0d019bc72003e01863791f30c5abdea5a1294cd6
