### ISSUE TITLE
HALO Unable to receive data

### ISSUE THREAD

**Issue by liuchao1** [opencpn-radar-pi/radar_pi#232]
The radar can initially receive data, but after running for a period of time, it can no longer receive data and will continue to display Spinning up

**Comment by liuchao1** [comment]
The radar is connected via wired.

**Comment by keesverruijt** [comment]
I assume you are running opencpn 5.8 and plugin 5.5.0. If not  please upgrade, if yes please upload your logfile.

**Comment by keesverruijt** [comment]
On windows disable the firewall, for testing.

**Comment by keesverruijt** [comment]
And make sure wireless network is not connected to the same network as the radar. Safest is to switch it off for testing.

**Comment by liuchao1** [comment]
I will try upgrade to opencpn 5.8 and plugin 5.5.0 ,for testing

**Comment by liuchao1** [comment]
Thanks! The problem has been resolved !  The radar is locked .  Another question, will using the OpenCPN radar be locked?
