### ISSUE TITLE
Where can I find older plugin versions?

### ISSUE THREAD

**Issue by keesverruijt** [opencpn-radar-pi/radar_pi#241]
Hello, 
Is it possible to upload old versions of Radar_pi (5.2 or 5.3 from spring 2022)? I haven't find it anywhere.

_Originally posted by @fneveu29 in https://github.com/opencpn-radar-pi/radar_pi/issues/238#issuecomment-1646782912_

**Comment by keesverruijt** [comment]
I think you mean where can you find older plugin versions and download them -- not upload?

The answer is: https://cloudsmith.io/~opencpn-radar-pi/repos/

**Comment by fneveu29** [comment]
Thanks

Le dim. 23 juil. 2023 à 11:25, Kees Verruijt ***@***.***> a
écrit :
