### ISSUE TITLE
Run standalone possible?

### ISSUE THREAD

**Issue by sailing12388** [opencpn-radar-pi/radar_pi#260]
Is it possible to run this plugin as a standalone application without OpenCPN running?

**Comment by Hakansv** [comment]
Quick answer: No.
Pls close this. Issues is about bugs and similar about the program.
Thanks.

**Comment by keesverruijt** [comment]
No, it is not. 

There is talk of creating a completely new implementation, which would be more independent from OpenCPN. 

What is your use case?

**Comment by sailing12388** [comment]
> No, it is not.
> 
> There is talk of creating a completely new implementation, which would be more independent from OpenCPN.
> 
> What is your use case?

Our use case is to control our B&G radar on our nav desk PC. This PC runs navigation software that is not OPCPN. We do run it at the moment but minimized so we can view/control the radar.

**Comment by sailing12388** [comment]
> No, it is not.
> 
> There is talk of creating a completely new implementation, which would be more independent from OpenCPN.
> 
> What is your use case?

Also, if anyone is looking into making this stand alone, we would be open to help fund that endeavor.

**Comment by keesverruijt** [comment]
Hi @sailing12388 the new implementation is now in active development, see https://github.com/keesverruijt/mayara
Feel free to join our Discord server: https://discord.gg/kC6h6JVxxC
