### ISSUE TITLE
Run it without Opencpn?

### ISSUE THREAD

**Issue by black-ghost-off** [opencpn-radar-pi/radar_pi#265]
Hello. There is a need to use Radar_PI plotter without Opencpn, are there any methods to cut this plugin and run it without Opencpn?

**Comment by Hakansv** [comment]
No, radar plugin needs the best navigational plotter i.e OpenCPN to work. :)
This plugin acts as the interface to a radar scanner. OpenCPN shows the radar image and handle user interface.

**Comment by black-ghost-off** [comment]
@Hakansv , as can i see, radar pi use own sub thread for draw own wx widget and that it draw on opencpn and communication with radars.

**Comment by avitase** [comment]
@black-ghost-off, https://github.com/opencpn-radar-pi/radar_pi/issues/264 is related to this.

**Comment by keesverruijt** [comment]
See https://github.com/keesverruijt/mayara
