### ISSUE TITLE
Navico: Side lob suppression. Miss Auto option

### ISSUE THREAD

**Issue by Hakansv** [opencpn-radar-pi/radar_pi#27]
Side lob suppression: Auto option is missing. When in Auto the status is though viewed correct. (Achieved after set to Auto using BR24radar_pi)

**Comment by canboat** [comment]
Oh can you try changing this:

HAVE_CONTROL(CT_SIDE_LOBE_SUPPRESSION, CTD_AUTO_NO, CTD_DEF_ZERO, CTD_MIN_ZERO, CTD_MAX_100, CTD_STEP_1, CTD_PERCENTAGE)

change CTD_AUTO_NO to CTD_AUTO_YES

**Comment by canboat** [comment]
In navico/NavicoControlSet.h

**Comment by Hakansv** [comment]
Yes, I can test and come back after live test. (Now home and have to go back to the boat for live test)

**Comment by Hakansv** [comment]
Tested OK. I couldn't make a direct push. A PR is waiting instead.
