### ISSUE TITLE
Navico: Timed transmitt. Wrong idle time. 

### ISSUE THREAD

**Issue by Hakansv** [opencpn-radar-pi/radar_pi#29]
Standby time is set to 0:40 minutes instead of 5 minutes and 1:40 instead of 10 minutes. (Debug code left over??)

**Comment by canboat** [comment]
oops yes change 

radar_pi.h:static const int SECONDS_PER_TIMED_IDLE_SETTING = 1 * 60;  // 5 minutes increment for each setting

to 5 * 60

**Comment by Hakansv** [comment]
OK, I'll test
