### ISSUE TITLE
After changing radar type trails duration shows "Off"

### ISSUE THREAD

**Issue by douwefokkema** [opencpn-radar-pi/radar_pi#38]
After changing radar type (after a "Reset radar types) trails duration shows "Off", whiles trails are on. See attached picture (multiple different radars working fine!)
![multiple_radars](https://user-images.githubusercontent.com/7831072/33202631-91df4b4a-d0fd-11e7-8d62-1993639f6d60.jpg)

**Comment by canboat** [comment]
interesting as the code should destroy + recreate all objects such as canvases and dialogs.

**Comment by canboat** [comment]
I don't understand this after checking myself. If you reset the radar types some settings revert to the initial default. What is the problem with that? I don't think a real user will ever reset the radar types (only when buying a new one...)

**Comment by douwefokkema** [comment]
The problem is that trails duration doesn't have an "Off" (if its right). Trails are switched off with the "Trails motion" button. In normal operation there is indeed no "Off" on trails duration. But after changing radar types there is an "Off" shown. See picture. his is not a serious error, but I still thought I should mention it.
A user will not REset radar types often. But I like to enable or disable a Navico B without destroying the Navico A.
