### ISSUE TITLE
GarminxHD : No range values in the PPI at lowest (1/8 Nm) range.

### ISSUE THREAD

**Issue by trudK45** [opencpn-radar-pi/radar_pi#4]
The header says it all.

**Comment by canboat** [comment]
Do you mean that there is no value in the top left, or that there are no values on the range rings?

**Comment by canboat** [comment]
1852/8 = 231,5 so let’s assume this comes in as 232, divided by 4 = 58
The current integer code checks 1852/32 = 57,875 = 57 ...

**Comment by trudK45** [comment]
In the PPI there is no range in the to left for what i can see. 
This what I see at minimum range (1/8 Nm).
![ppi_no_range](https://user-images.githubusercontent.com/10415016/32579473-ff50f128-c4d8-11e7-8078-7791dcf66283.jpg)

**Comment by canboat** [comment]
Can you try again with commit 08a5758 applied?

**Comment by trudK45** [comment]
Yes the 1/8 is ok now.
Other ranges are sometimes missing values. Here the inner most ring is missing value.
The number given on the next largest ring 1.12473 is difficult to comprehend.
On the garmin plotter the number of rings vary with range. In this case there are three rings
1/2 Nm between. This would be more elegant I think though it might be more work for you. 
Example 1 1/2 Nm.
![ppi_one_and_one_half_nm](https://user-images.githubusercontent.com/10415016/32580442-2e40a61e-c4dd-11e7-829f-a76d03bfeb8e.jpg)

**Comment by canboat** [comment]
Let me know what you think now, it only draws those rings that can be represented in nice units.

**Comment by trudK45** [comment]
Perfect. Only nice "round" numbers and it sets rings exactly like the Garmin Plotter.
Nice work. Only objection I have is that the outer most value is right beside the 135 degree angle value.
Maybe I am a bit fuzzy but I thing it would be a little bit easier to read if the range numbers were put at another angle. Say in between 135 and 120 degree, or 1/4 of the way up. Does this make sense ?

**Comment by canboat** [comment]
Actually I'm thinking I am going to reduce the clutter by only drawing the angle every 30 degrees, like my MFD.
