### ISSUE TITLE
Timed transmit should stay on when an ARPA target is detected

### ISSUE THREAD

**Issue by douwefokkema** [opencpn-radar-pi/radar_pi#40]
ARPA targets detected in a guard zone will get lost after the Tx period ends. Targets might pass without an alarm through the guard zone.

**Comment by canboat** [comment]
Good idea.

**Comment by Hakansv** [comment]
I may not understand but if no guard alarm is checked but only ARPA ON the timed transmit is not interrupted. It's only interrupted by a guard alarm - or? (I have no moving targets, can't check)
And if the guard alarm is checked the TimedTransmit would end and start transmission if there's a target in the zone. Irrespective of ARPA ON is checked or not.

**Comment by douwefokkema** [comment]
Håkan: to avoid returns from birds or sea-state raising an alarm you might only use ARPA and not guard alarm. And targets may move outside the zone and still be dangerous.

I think this item should not be seen as an enhancement but as a necessary condition to use ARPA with timed transmit. Implemented in a44a53f3ac.

**Comment by Hakansv** [comment]
OK, convinced.

**Comment by douwefokkema** [comment]
Tested by Håkan I saw somewhere. To be reopened if someone disagrees.
