### ISSUE TITLE
No targets shown in PPI window for 4G

### ISSUE THREAD

**Issue by douwefokkema** [opencpn-radar-pi/radar_pi#41]
Targets shown on overlay and in Garmin PPI windkow don't show in 4G window. Contours of these targets do show in the 4G window.
![multiple_radars](https://user-images.githubusercontent.com/7831072/33203121-51f1400e-d0ff-11e7-8d6f-a310885e388e.jpg)

**Comment by douwefokkema** [comment]
In case we only run the 4G radar, targets are shown as they should.

**Comment by canboat** [comment]
The menu button shows that you have not enabled AIS/ARPA — the button says “Show AIS/ARPA” in your screen shot which means that it is not enabled now.

**Comment by douwefokkema** [comment]
Then the text on the button is wrong or at least confusing. 
Buttons have two functions: indicate what it does and display the current value. This button should read:
"Show / hide AIS", and on the second line "Show"

**Comment by douwefokkema** [comment]
Further discussed in #39
