### ISSUE TITLE
Crash when starting with no radars selected

### ISSUE THREAD

**Issue by douwefokkema** [opencpn-radar-pi/radar_pi#49]
When starting the pi without radars selected (reset radars) O crashes when clicking "Radar control.." in the context menu. Only way to get out of this is accessing preferences from the O tools plugin menu and add a radar.

**Comment by Hakansv** [comment]
Since there's no default radar type could we check for that on "Radar Control..." button click and if ri->m_radar_type = RT_MAX open the settings dialog?
