### ISSUE TITLE
Inconsistent Radar Standby, Transmit and Back button. 

### ISSUE THREAD

**Issue by trudK45** [opencpn-radar-pi/radar_pi#52]
From the start menu, when you press "Radar Standby" you expect the radar to start transmitting but this does not happen. You enter a new menu with the same button "Radar Standby". In this menu at the top there is a "<<BACK" button that you would expect to get you back to the previous menu. Pressing this button does not get you back. It gets you further down the menu hierarchy.
To get back you must press "Radar Transmit" button and this does not set the radar in standby. To do that you have to press the new "Radar Transmit" button.
I know that the text on the buttons represent current state but what is then the "<<BACK" state.
I  fear that trying to fix all these anomalies will take to much energy right now and we will not get it right anyway.
For instance, I don't like the fact that you have to start transmitting to get access to functions like No transmit zone, Antenna position and Bearing alignment but I can live with that for now.

**Comment by canboat** [comment]
I think these are all fixed now. See #39.
