### ISSUE TITLE
Auto range does not cover the whole chart.

### ISSUE THREAD

**Issue by trudK45** [opencpn-radar-pi/radar_pi#60]
If you pan the chart so that the boat is at the far right on the screen you have no radar coverage on the on the left of the screen. The range on this plot is set to 4 Nm and the distance to the left of the chart is > 7 Nm.

![auto range](https://user-images.githubusercontent.com/10415016/33608965-2048c1ae-d9be-11e7-8b79-f8f4d3359879.jpg)

**Comment by trudK45** [comment]
Maybe this is how we want it ?

**Comment by canboat** [comment]
I think this is what my plotter does, so I am not against leaving it like this.

**Comment by trudK45** [comment]
Ok, this is how the Garmin plotter seem to work as well. The original gradar_pi and my gxradar_pi works differently. There the range is chosen so that the range covers the chart.
I think it's ok to have it as it is now. I will close the issue. Any other comments ?

**Comment by canboat** [comment]
Works as designed, I would say.
