### ISSUE TITLE
No ring at extreme range.

### ISSUE THREAD

**Issue by trudK45** [opencpn-radar-pi/radar_pi#61]
Activating the option under preferences  "Show ring at extreme range" there is no ring.

**Comment by Hakansv** [comment]
On BR24 and emulator I've a ring. You don't use OCPN distance rings do you? For me they often cover the radar ring.
The pointer was on the ring at shot event. 
![bild](https://user-images.githubusercontent.com/7202854/33612953-858637bc-d9d3-11e7-9b0e-401e1b72d9de.png)

**Comment by trudK45** [comment]
On Garmin xHD there is nor ring on the chart. There is on o the PPI .

**Comment by trudK45** [comment]
Could this have to do with the fact that the number of spokes vary on the Garmin ?
I would suspect so looking at the code.

**Comment by canboat** [comment]
I do see a ring, on both PPI and overlay. Don't get confused with the image, it is a radar image from Honduras overlayed onto Holland :-)

<img width="919" alt="screen shot 2017-12-08 at 18 44 00" src="https://user-images.githubusercontent.com/1608058/33778188-eac94d46-dc47-11e7-9712-4a7f773c0a0e.png">

**Comment by trudK45** [comment]
What spoke length are you running with ?

**Comment by canboat** [comment]
It's your file!

**Comment by trudK45** [comment]
Well, I can't see any ring here. I have activated the Show ring at extreme range". I have Overlay transparency = 20 %. I am transmitting. Is it meeded ? Is there anything else needed ?

**Comment by canboat** [comment]
Nope, that should be enough. It can be quite far away ...

**Comment by trudK45** [comment]
I have radar range = 1 Nm and scale on chart so I can see 48 Nm. No ring.
No ring if I rescale so I can see 5 Nm. Ring should be a small distance outside "No transmit zone"

**Comment by trudK45** [comment]
No, that is not enough. You have to have set "Show target trails on overlay" also.
This must be wrong.
