### ISSUE TITLE
Distance rings in PPI is wrong.

### ISSUE THREAD

**Issue by trudK45** [opencpn-radar-pi/radar_pi#65]
When you specify inner and outer distance in the the PPI they do not align with distance rings.
The Guard zone seems correct. The Guard zone inner border is set to 3 and the outer to the distance to a ship. The ships distance can be seen in the AIS Target Query and corresponds with the outer guard border.
I.e. AIS and Guard zone distance correlate but not the radar distance rings. This seems to be the case on all ranges.

![image](https://user-images.githubusercontent.com/10415016/33790620-b5b34a58-dc79-11e7-97b4-224f97ee59e1.png)

**Comment by canboat** [comment]
Does this work for you now?

**Comment by trudK45** [comment]
Yes this is now good. One thing though. If you shut down OPCN with guard zone active, then when you start OPCN the guard zone does not show. Not a big deal but it does not get back to the same state. You have to start transmitting before the guard zone appears.

**Comment by canboat** [comment]
> On 10 Dec 2017, at 15:00, trudK45 <notifications@github.com> wrote:
> 
> Yes this is now good. One thing though. If you shut down OPCN with guard zone active, then when you start OPCN the guard zone does not show. Not a big deal but it does not get back to the same state. You have to start transmitting before the guard zone appears.
> 
> 

When the plugin has no idea of the radar range (and is never told it) it refuses to draw anything, right now. I can fix this.

**Comment by trudK45** [comment]
Is it not told by the received packets from the radar ?

**Comment by canboat** [comment]
It was looking at the 'real' radar range received, e.g. the spoke data. Fixed that now.
