### ISSUE TITLE
ARPA detection is not working since some of the last commits

### ISSUE THREAD

**Issue by Hakansv** [opencpn-radar-pi/radar_pi#68]
Tested with Emulator and 4GA radar. Neither works. Guard alarm is still working.

**Comment by canboat** [comment]
It works fine for me with origin/master, i.e. without your pull request.

A common pitfall is to disable AIS/ARPA on the PPI display, which means you don't see the detected targets on the PPI.

**Comment by Hakansv** [comment]
1. Yes I'm on origin/master wo changes. Latest pull 5 minutes ago. 
2. It's not about PPI. (I use overlay). There's no ARPA contour at all so the detection process is not started. 
I'm not sure how to trace this. Any advice?

**Comment by canboat** [comment]
The first thing to do is to see if you don't see any ARPA contours in the PPI either. (I see both...)

Second is to try to reproduce it with a 'well known pcap', e.g. one in the examples directory.

**Comment by Hakansv** [comment]
As said, no contours. Nether in PPI nor overlay.
And, Yes I use the same pcap(s) as for the last two years. Radar type is set to 4G A as usual.
The ARPA detection was there two-three days ago. Also in the emulator. Neither works now.
I'm on Win10 also as usual.

**Comment by canboat** [comment]
Maybe Douwe can help, I don’t have this issue and I am busy working on timed transmit.

**Comment by douwefokkema** [comment]
Just tried on origin/master, fae3bff4. All fine.

**Comment by Hakansv** [comment]
OK thanks for testing.  Something on my (build?) system then.  Hmmm

**Comment by douwefokkema** [comment]
I also tested your PR, just perfect, but not tested with AIS targets (don't have them here).
![targets](https://user-images.githubusercontent.com/7831072/33806289-5a0830c6-ddc6-11e7-9339-73c9015b5882.jpg)

**Comment by trudK45** [comment]
Here we got an island moving to the NW at 2.35 knots.

![image](https://user-images.githubusercontent.com/10415016/33806598-8e3d884a-ddc2-11e7-8679-4f2392d82bc5.png)

**Comment by trudK45** [comment]
I am new to ARPA and so need to ask. Why are only certain targets registered ?
Do you discard targets that have AIS transmitters ?

![image](https://user-images.githubusercontent.com/10415016/33806694-cdabbc8a-ddc3-11e7-8842-28eb8c2e1df9.png)

**Comment by trudK45** [comment]
By the way. The Radar symbol in the menu is now a zig-zag piece.

**Comment by canboat** [comment]
> Do you discard targets that have AIS transmitters ?

Yes, nice no?

> The Radar symbol in the menu is now a zig-zag piece.

This is common if you run under a debugger without the correct directory structure. I just tested a real installer and then I did not see any issues with the icon.

**Comment by canboat** [comment]
> Here we got an island moving to the NW at 2.35 knots.

Douwe?

**Comment by trudK45** [comment]
I am running a real installer and still get the zig-zag.

**Comment by canboat** [comment]
Can you try finding this yourself, I'm busy on timed transmit.

**Comment by trudK45** [comment]
This was surprising. Reinstalled the plugin and now it's ok.

**Comment by douwefokkema** [comment]
"Do you discard targets that have AIS transmitters ?"
Yes, when an ARPA target is closer than a certain limit to an AIS target the pi does not send the target to O, the contours are shown.

"Here we got an island moving to the NW at 2.35 knots."
On the island there are multiple unstable blobs. The ARPA system can't make much sense out of these blobs. If the radar would show the island as one stable blob there would be no problem. ARPA targets do need some kind of human interpretation.

**Comment by douwefokkema** [comment]
"Do you discard targets that have AIS transmitters ?"
Yes, when an ARPA target is closer than a certain limit to an AIS target the pi does not send the target to O, the contours are shown.

"Here we got an island moving to the NW at 2.35 knots."
On the island there are multiple unstable blobs. The ARPA system can't make much sense out of these blobs. If the radar would show the island as one stable blob there would be no problem. ARPA targets do need some kind of human interpretation.

**Comment by Hakansv** [comment]
Found it!!!
This error was on one of my PCs only. So checked the config file for anomalous setting and found:
Radar0MinContourLength=33620738 where default setting should be 6. 
How and when the abnormal value was set I don't know. When corrected ARPA is working nice also on that PC. Sorry for any trouble for you but it may be a lesson learned?
