### ISSUE TITLE
Raymarine support

### ISSUE THREAD

**Issue by BrannJoly** [opencpn-radar-pi/radar_pi#77]
Hi,
I was wondering if you had considered supporting Raymarine radars ? I have one, and I'm thinking about looking into it, but maybe there's a good reason why it hasn't been done before ? 

Cheers,
Brann

**Comment by canboat** [comment]
None of the current developers have a Raymarine radar, so we can’t work on this.

Feel free to implement it yourself, it is now much easier than before. The most difficult part is analyzing the traffic between the radar and the MFD using an IP packet analyzer such as tcpdump. Once you have this, we’re willing to help you set up the code and fix bugs, but testing needs to be done by someone with access to the physical radar.

An alternative, if you are not a C++ developer, is to donate a Raymarine MFD and radar to one of the existing developers :-)

**Comment by canboat** [comment]
See #79 .
