### ISSUE TITLE
GarminxHD : ScanSpeed Auto button. What is it good for ?

### ISSUE THREAD

**Issue by trudK45** [opencpn-radar-pi/radar_pi#8]
Scan speed Fast and Slow works fine but I have a hard time figuring out what the Auto button is used for.
When activating it the value Slow or Fast disappears. To get it back you need to toggle + or -.

**Comment by canboat** [comment]
The auto button was showing everywhere even where it shouldn't. That was fixed in commit 951f470.

Can you test that this works now as I don't have a live radar?

**Comment by trudK45** [comment]
Yes this works fine now.
